<#
  Claude Usage — Windows installer (system-tray indicator)
  ------------------------------------------------------------------
  Run in PowerShell (from the repo's windows\ folder):
      powershell -ExecutionPolicy Bypass -File install-claude-usage-windows.ps1

  Installs claude-usage-tray.ps1 to %LOCALAPPDATA%\ClaudeUsageBar, makes it launch
  hidden at login, checks prerequisites, and starts it now. Safe to re-run.
#>
$ErrorActionPreference = 'Stop'
Write-Host '=== Claude Usage - Windows installer ===' -ForegroundColor Cyan

$SrcTray  = Join-Path $PSScriptRoot 'claude-usage-tray.ps1'
if (-not (Test-Path $SrcTray)) { Write-Host "!! Missing $SrcTray (run this from the repo's windows\ folder)" -ForegroundColor Red; exit 1 }

# --- 1. install location ---
$InstallDir = Join-Path $env:LOCALAPPDATA 'ClaudeUsageBar'
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
$DstTray = Join-Path $InstallDir 'claude-usage-tray.ps1'
Copy-Item -Force $SrcTray $DstTray
Write-Host "- Plugin installed: $DstTray"

# --- 2. hidden launcher (no console flash on boot) ---
$Vbs = Join-Path $InstallDir 'launch-hidden.vbs'
@"
' Auto-generated by install-claude-usage-windows.ps1 - launches the tray app with no window.
CreateObject("Wscript.Shell").Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$DstTray""", 0, False
"@ | Set-Content -Path $Vbs -Encoding ASCII
Write-Host "- Launcher written: $Vbs"

# --- 3. run at login (Startup folder shortcut) ---
$Startup  = [Environment]::GetFolderPath('Startup')
$Shortcut = Join-Path $Startup 'Claude Usage.lnk'
$ws = New-Object -ComObject WScript.Shell
$lnk = $ws.CreateShortcut($Shortcut)
$lnk.TargetPath  = 'wscript.exe'
$lnk.Arguments   = """$Vbs"""
$lnk.WorkingDirectory = $InstallDir
$lnk.Description  = 'Claude Usage tray indicator'
$lnk.Save()
Write-Host "- Login item created: $Shortcut (starts on boot)"

# --- 4. prerequisite checks ---
$CredPath = Join-Path $env:USERPROFILE '.claude\.credentials.json'
if (Test-Path $CredPath) {
  Write-Host "- Claude Code login: found ($CredPath)"
} else {
  Write-Host "!! Not logged in to Claude Code on this PC." -ForegroundColor Yellow
  Write-Host "   Run 'claude' once and sign in, then this bar will populate."
}
$psv = $PSVersionTable.PSVersion
Write-Host "- PowerShell: $psv"

# --- 5. (re)start it now ---
Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" |
  Where-Object { $_.CommandLine -like '*claude-usage-tray.ps1*' } |
  ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
Start-Process 'wscript.exe' -ArgumentList """$Vbs"""
Write-Host '- Tray app launched.'

Write-Host ''
Write-Host 'Done. Look at the system tray (bottom-right) for a two-bar icon:' -ForegroundColor Green
Write-Host '  top bar = session (5h), bottom bar = weekly. Hover for %/reset; right-click to Refresh/Quit.'
Write-Host 'To remove: delete "'$Shortcut'" and the folder "'$InstallDir'".'
